name: R6RS Portable FFI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Scheme-env-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: target
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libgc-dev zlib1g-dev libffi-dev curl libx11-dev
      - name: Install scheme-env
        run: |
          curl https://raw.githubusercontent.com/ktakashi/scheme-env/master/bin/install.sh | bash
          echo "$HOME/.scheme-env/bin" >> $GITHUB_PATH
      - name: Install Implementations
        run: |
          scheme-env install sagittarius
          scheme-env install chez
      - name: Run test
        working-directory: target
        run: ./ci-test.sh

  Makefile-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: target
      - name: Install Implentations
        run: |
          sudo apt update
          suto apt -y install guile-3.0 racket
      - name: Run test
        working-directory: target
        run: make guile racket
